# Generated by Django 4.2.23 on 2025-06-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='apellido_materno',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='apellido_paterno',
            new_name='paciente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='rut',
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
