# Generated by Django 4.2.23 on 2025-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_rename_apellido_materno_cita_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='apellido_materno',
            field=models.CharField(default='SinApellido', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='apellido_paterno',
            field=models.CharField(default='SinApellido', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre',
            field=models.CharField(default='SinNombre', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_id',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
